name: physiq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  cloud_functions: ^6.0.4
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5
  firebase_remote_config: ^6.1.2
  firebase_performance: ^0.11.1+2
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  table_calendar: ^3.1.2
  dotted_border: ^2.1.0
  shared_preferences: ^2.2.3
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  http: ^1.2.1
  share_plus: 10.1.4
  fl_chart: ^1.1.1
  url_launcher: ^6.2.5
  package_info_plus: ^9.0.0
  image_picker: ^1.0.7
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
